### ISSUE TITLE
on create error

### ISSUE THREAD

**Issue by joramkimata** [pixo-vin/android-sdk#1]
Please assist i got this error when i started the program

![2](https://cloud.githubusercontent.com/assets/4988463/15627392/135c94ea-24eb-11e6-9a7b-c446d6198f4c.PNG)

**Comment by youngest** [comment]
It doesn't appear that you have completely followed the instructions from the README file. AndroidScanLib.gradle needs to be fully merged with your projects gradle file. Everything in the dependencies section is required:

> dependencies {
>     compile 'com.squareup.retrofit:retrofit:1.9.0'
>     compile 'com.google.code.gson:gson:2.3.1'
>     compile 'com.android.support:appcompat-v7:23.1.1'
>     compile 'com.pixotech.android.scanner.library:AndroidScanLib@aar'
> }
