### ISSUE TITLE
Add react-native SDK

### ISSUE THREAD

**Issue by ymahnovskyy** [pixo-vin/android-sdk#11]
There is a need to add vin scanning to react-native app. Do you have any plans to implement SDK for react-native?

**Comment by pixovin** [comment]
Hello Yuriy,

Thanks so much for reaching out. Updating the SDK for react-native is not
part of our current project plan. We have received many requests for
Xamarin and Cordova, but this is the first for react-native.

However, we are part of a development firm and are avaialble for custom
consulting. I have been told that it would take fairly significant effort
to make Capture work with react-native, but I would be more than happy to
provide a cost estimate for the update. Is that something you would be
interested in?

Thanks in advance,



*Shawna Culp*

Product Manager
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444 ext. 12
pixotech.com
pixoVIN.com

**Comment by ymahnovskyy** [comment]
Thanks for quick response. Now I've found some competitor product which support react-native. So, I'll ask about a cost estimate if we need it.
