### ISSUE TITLE
Pixo Vin Scanner Latest Version With Kotlin Compiler

### ISSUE THREAD

**Issue by Gagege** [pixo-vin/android-sdk#2]
# I have been having an issue using the latest version of the Pixo Vin Android SDK in a Kotlin project. I just thought you might like to be aware that your latest version will not compile in a Kotlin project. I have converted your sample Android app to Kotlin and attached it. You’ll see that the build fails with this error:

```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.pixotech.android.scanner.library.ScannerActivity, unresolved supertypes: BarcodeScannerCallback
    class com.pixotech.android.scanner.library.ScannerFragment, unresolved supertypes: BarcodeScannerCallback
```

I’ll be sticking with an older version of your library for now, but I’d like to be able to update it. Maybe you know of, or can figure out a work around. That would be great! If nothing else, I figured you’d like to know since Kotlin is getting pretty popular and I bet more of your users are going to be using it and running into this issue.
[SampleApplication.zip](https://github.com/pixo-vin/android-sdk/files/378939/SampleApplication.zip)

**Comment by youngest** [comment]
@Gagege Thank you for providing a Kotlin project for us to test against! This build error is resolved in the latest release, tagged r14.

**Comment by Gagege** [comment]
@youngest Thank _you_!

I just tried out r14 and it works great!
