### ISSUE TITLE
Slow Focus Speed

### ISSUE THREAD

**Issue by richehmer** [pixo-vin/android-sdk#4]
We've noticed the focus speed is slow in the app. It seems more like 'video' focus speed than 'photo' focus speed. Does the API have any mechanisms to increase focus speed? Or are there any plans to increase the default speed in a future version? :-)

Edit: comment from the user "I feel like I'm positioning the device a reasonable distance from a barcode, but then I have to wait ~2 seconds for the camera to re-focus on it before it can read it. (This is on a Nexus 6P)"

**Comment by winzig** [comment]
@pixovin Any feedback on this issue?

**Comment by aftabsikander** [comment]
I also faced this issue, plus user's hands need to be steady while scanning otherwise, it would refocus again in loop

**Comment by pixovin** [comment]
Hi Aftab,

This issue with newer Android devices and ones running the latest version
of Android was resolved a few updates ago. We have not tested directly on
the Pixel, but it is very possible that the problems you are having there
are the same that have been fixed on other devices.

On many devices our SDK is using a continuous auto-focus mode with custom
timing that has worked well for us over the years. On devices which do not
support that feature it falls back to Android's in-built continuous
auto-focus modes.

Thanks,


*Shawna Culp*

Pixo *|* Business and Product Coordinator
121 W. Goose Alley
Urbana, IL 61801
(217) 344-0444
pixotech.com
pixoVIN.com
